package models

data class Product(
    val premiumRate: Double,
    val levy: Double,
    val minimumRate: Double,
    val maximumRate: Double,
    val code: String,
    val policyPrefix: String,
    val claimsPrefix: String,
    val coverType: CoverType,
    val insuranceCompanyIndex: Int,
    val wordingsPath: String = "/Users/lucksonmwanambulo/Downloads/POL_WRD.pdf",
    val clausesPath: String = "/Users/lucksonmwanambulo/Downloads/POL_WRD.pdf",
)

val products = arrayListOf(
    Product(
        premiumRate = 5.0,
        levy = 3.0,
        minimumRate = 2.0,
        maximumRate = 5.0,
        code = "MGITP",
        policyPrefix = "MGIP",
        claimsPrefix = "MGIC",
        coverType = CoverType.THIRD_PARTY,
        insuranceCompanyIndex = 4,
    ),
    Product(
        premiumRate = 4.0,
        levy = 1.0,
        minimumRate = 2.0,
        maximumRate = 3.0,
        code = "MGIAC",
        policyPrefix = "MGIP",
        claimsPrefix = "MGIC",
        coverType = CoverType.ACT_ONLY,
        insuranceCompanyIndex = 4,
    ),
    Product(
        premiumRate = 5.0,
        levy = 2.0,
        minimumRate = 2.0,
        maximumRate = 3.0,
        code = "MGICP",
        policyPrefix = "MGIP",
        claimsPrefix = "MGIC",
        coverType = CoverType.COMPREHENSIVE,
        insuranceCompanyIndex = 4,
    ),
    Product(
        premiumRate = 5.0,
        levy = 2.5,
        minimumRate = 2.0,
        maximumRate = 3.0,
        code = "MGITPFT",
        policyPrefix = "MGIP",
        claimsPrefix = "MGIC",
        coverType = CoverType.THIRD_PARTY_FIRE_AND_THEFT,
        insuranceCompanyIndex = 4,
    ),
)
